name: Docker Build Python and upload to Jfrog

on: [push]
  
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        
      - name: Login to JFrog ğŸ¸  
        uses: docker/login-action@v1
        with:
          registry: nipusa2027.jfrog.io
          username: test
          password: Test20240515

      - name: Build and push ğŸ³
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nipusa2027.jfrog.io/longqing-docker/python-test:latest
          context: ./hello-world-docker-action
          
